name: HiFiNi 自动签到2

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Start Time
        run: "echo Start time: $(date)"
        
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Set go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.14'

      - name: HIFINI 自动签到（带自动重试）
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: error
          command: |
            go run main.go
        env:
          COOKIE: ${{ secrets.COOKIE }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
